<a href="https://colab.research.google.com/github/wldud01/Pytorch_tutorial/blob/main/Tensor_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
### What is Pytorch
pytorch is a python based scientific computin package serving two broad purposes:
- A replacement for Numpy to use the power of GPUs and other accelerators
- An automatic differentiation library that is useful to implement neural networks


### Tensors
- be similar to arrays and matrices.
- to encode the inputs and outputs of a model, as well as the model's parameters.
- similar to Numpy's ndarrays,


In [1]:
import torch
import numpy as np


In [2]:
#@title Tensor Initialization

# automatically inferred
data =[[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
#@title Initialize one
x_ones = torch.ones_like(x_data)
print("ones Tensor", x_ones)

ones Tensor tensor([[1, 1],
        [1, 1]])


In [7]:
#@title Overrides the datatype of x_Data
x_rand = torch.rand_like(x_data,dtype=torch.float)
print("Random tensro", x_rand)

Random tensro tensor([[0.9778, 0.9529],
        [0.4919, 0.8710]])


In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print("rand tensor", rand_tensor)
print("ones tensor", ones_tensor)
print("zeros tensor", zeros_tensor)


rand tensor tensor([[0.0998, 0.4167, 0.7871],
        [0.7582, 0.6358, 0.0295]])
ones tensor tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros tensor tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
#@title Tensor Attributes
tensor = torch.rand(3,4)

print("shape",tensor.shape)
print("type",tensor.dtype)
print("device",tensor.device)

shape torch.Size([3, 4])
type torch.float32
device cpu


In [13]:
#@title Tensor operations
# Each of them can be run on the GPU(at typically higher speeds than on a CPU)
if torch.cuda.is_available():
  tensor = tensor.to("cuda")
  print("device tensor is stored on",tensor.device)
else:
  print("cuda disabled")

cuda disabled


In [15]:
tensor = torch.ones(4,4)
# All row , only index 1 col change 1 to zeros
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
tensor[:,1] = 1
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
# same as np.concat()
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [25]:
#@title multiplying tensors

# mul is same as *
tensor_a = torch.ones(2,3)
tensor_b = torch.ones(2,3)
tensor_a[:,2] = 3

print("tensor_matmul", tensor_a.mul(tensor_b))
print("tensor_multiplying", tensor_a*tensor_b)

tensor_matmul tensor([[1., 1., 3.],
        [1., 1., 3.]])
tensor_multiplying tensor([[1., 1., 3.],
        [1., 1., 3.]])


In [26]:
#@title matmul tensors
print(tensor_a.matmul(tensor_b.T))
print(tensor_a @ tensor_b.T)

tensor([[5., 5.],
        [5., 5.]])
tensor([[5., 5.],
        [5., 5.]])


In [29]:
#@title _ suffix are in place operations
print(tensor_a)
tensor_a.add_(10)
print(tensor_a)

tensor([[1., 1., 3.],
        [1., 1., 3.]])
tensor([[11., 11., 13.],
        [11., 11., 13.]])


In [30]:
# if we want to share tensor and array
# tenors on the CPU and numpy arrays can share their underlying memory locations
# Changing one will change the other

t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [31]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [32]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [34]:
np.add(n,2,out=n)
print(n)
print(t)

[4. 4. 4. 4. 4.]
tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
